name: security
on:
  push:
  pull_request:
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
  powershell-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
      - name: Analyze PowerShell
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path .\modules,.\scripts -Recurse -Severity Warning,Error
